language: rust
sudo: false

script:
    - cargo build --verbose --manifest-path cargo-apk/Cargo.toml

after_success: 
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path glue/Cargo.toml --no-verify
