[package]
name = "cargo-apk"
version = "0.1.4"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "MIT"
description = "Cargo subcommand that allows you to build Android packages"
repository = "https://github.com/tomaka/android-rs-glue/tree/master/cargo-apk"

[dependencies]
rustc-serialize = "0.3.19"
term = "0.4.4"
toml = "0.1.28"
